Release membrane_framerate_converter_plugin v0.3.0
membraneframework/membrane_framerate_converter_plugin pull request #5
Opened 2021-11-30 11:53 UTC by andpodob

### Release "Newly Needed Gull"

| Project | New Version |
|---|---|
| membrane_h264_ffmpeg_plugin | `0.15.0` |

<sup>proudly automated with <a href="https://github.com/membraneframework/sebex">Sebex</a></sup>

2021-12-22 15:43 UTC, bblaszkow06 requested changes

2021-12-22 15:43 UTC, bblaszkow06 commented on test/membrane_framerate_converter_test.exs
> +    test "convert video with gifven pts" do
```suggestion
    test "convert video with given pts" do
```

2021-12-22 15:43 UTC, bblaszkow06 commented on lib/membrane_framerate_converter.ex
> +  - as the 1.9(3)s and 1.8(6)s timestamps exceed last timestamp of the input video.
Actually, this seems like a description of a bug, not a feature, this should not happen. If the output has 15 fps, it either needs 30 frames or is shorter than the input.
Therefore, the last output timestamp should not be `smaller or equal last timestamp` but rather `smaller or equal than the last timestamp **+ input frame duration**`
In the example above - `1.9(3)s and 1.8(6)s` are within 1.8s + 1/5 s = 2s

2021-12-22 15:43 UTC, bblaszkow06 commented on mix.exs
> +      {:membrane_h264_ffmpeg_plugin, "~> 0.15.0", only: :test}
The plugin was bumped twice due to sebex, the current version is (or should soon be) 0.16.2

2021-12-27 09:44 UTC, agga1 commented on lib/membrane_framerate_converter.ex
> +  - as the 1.9(3)s and 1.8(6)s timestamps exceed last timestamp of the input video.
yes, but there is a problem when input video has variable frame rate - there is no way to tell how long the last frame should be displayed, so I just generated timestamps until the last one for all cases.
I can however check if input framerate exists and only then add input frame duration.

2021-12-27 14:12 UTC, bblaszkow06 requested changes

2021-12-27 14:12 UTC, bblaszkow06 commented on lib/membrane_framerate_converter.ex
> +    round(Membrane.Time.second() * denom / num)
To make the calculations consistent, I'd use Ratio here and use this function for both bumping timestamp and best_last_timestamp calculation

2021-12-27 14:12 UTC, bblaszkow06 commented on lib/membrane_framerate_converter.ex
> +    best_last_timestamp = last_buffer.pts + input_frame_duration - div(output_frame_duration, 2)
It took me a while to understand what's the `div` here for. I believe it deserves an explanation in a comment.
It's here to include the repetition of a last frame that would have been generated if another frame came with PTS equal to `last_buffer.pts + input_frame_duration`, am I right?

2021-12-28 11:05 UTC, bblaszkow06 approved these changes

2021-12-28 11:13 UTC, merged